[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type","center", "--transition-step","15", "--transition-fps","60"]
set = true

[templates.hyprland]
input_path = '/home/TheMaz/.config/matugen/templates/hyprland-colors.conf'
output_path = '/home/TheMaz/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'


[templates.waybar]
input_path = '/home/TheMaz/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'
